name: ROS 2 CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test the project
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build and test
        uses: ichiro-its/ros2-ci@v0.4.1
        with:
          ros2-distro: foxy
          apt-packages: git ros-foxy-dynamixel-sdk libopencv-dev 
          pre-build: git clone https://github.com/ichiro-its/shisen_interfaces /ws/shisen_interfaces
